<?php

/**
 * @file
 * Installation code for Droogle.
 */

/**
 * Implements hook_uninstall().
 */
function droogle_uninstall() {
  variable_del('droogle_clientid');
  variable_del('droogle_secret');
  variable_del('droogle_password');
  variable_del('droogle_title_text');
  variable_del('droogle_og_field_gdrive_client_id');
  variable_del('droogle_og_field_gdrive_client_secret');
  variable_del('droogle_default_domain');
}


/**
 * Update variable names.
 */
function droogle_update_7401() {
  if ($val = variable_get('droogle_og_cck_field_gdrive_client_id')) {
    variable_set('droogle_og_field_gdrive_client_id', 'field_' . $val);
    variable_del('droogle_og_cck_field_gdrive_client_id');
  }
  if ($val = variable_get('droogle_og_cck_field_gdrive_client_secret')) {
    variable_set('droogle_og_field_gdrive_client_secret', 'field_' . $val);
    variable_del('droogle_og_cck_field_gdrive_client_secret');
  }
  // Unused
  variable_del('droogle_default_domain');
}
